In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg
import cv2

In [ ]:
image_path="images/lena_color_256.tif"
image=mpimg.imread(image_path)
plt.imshow(image)

In [ ]:
image.shape

In [1]:
import cv2

In [2]:
image_path='day2\resources\lena.png'


In [5]:
c=cv2.imread(image_path)
c

In [6]:
c

In [ ]:
#color convert
c=cv2.cvtColor(c,cv2.COLOR_BGR2RGB)
plt.imshow(c)

In [ ]:
c.shape


In [ ]:
c.min()

In [ ]:
#understanding composition of color image
def show_color_channel(image):
    color = ('r','g','b')
    for i,col in enumerate(color):
        channel=image[:,:,i]
        plt.subplot(1,3,i+1)
        plt.imshow(channel,cmap='gray')
        plt.title(f'{col} channel')
        plt.axis('off')
    plt.show()
show_color_channel(c)

In [7]:
import numpy as np

In [9]:
#understanding filter
sobel=np.array([[-1,0,1],
                [-2,0,2],
                [-1,0,1]])
print(sobel)


[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]


In [10]:
print(sobel.T)

[[-1 -2 -1]
 [ 0  0  0]
 [ 1  2  1]]
